---
- name: "Import elasticsearch GPG key"
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: "Configure Elasticsearch repository"
  copy:
    src: "elasticsearch.repo"
    dest: "/etc/yum.repos.d/elasticsearch.repo"
  become: true

- name: "Install Filebeat"
  yum:
    name: filebeat
    state: latest
  notify: "Start Filebeat"
  become: true
