---
- name: "Preflight Checks"
  include_tasks: "00-preflight-checks.yml"

- name: "Install Filebeat"
  include_tasks: "01-install.yml"
  when: install

- name: "Configure Filebeat"
  include_tasks: "02-configure.yml"
  when: configure
