---
- name: "Start Filebeat"
  systemd:
    name: filebeat
    enabled: yes
    state: started
  become: true

- name: "Restart Filebeat"
  systemd:
    name: filebeat
    state: restarted
  become: true
